# Generated by Django 2.2.10 on 2021-07-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20210716_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='questionchoice',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
