# Generated by Django 2.2.10 on 2021-07-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20210717_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswersquestion',
            old_name='question_id',
            new_name='question',
        ),
    ]
