# Generated by Django 2.2.10 on 2021-07-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20210717_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswersquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='useranswersquestion',
            name='user_survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.UserTakesSurvey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswersquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='surveys.Question'),
        ),
        migrations.AlterField(
            model_name='usertakessurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_obj', to='surveys.Survey'),
        ),
        migrations.AlterField(
            model_name='usertakessurvey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='surveys.SimpleUser'),
        ),
    ]
